### ISSUE TITLE
Adding hPa (hectopascal) and inHg (inch of mercury) to PRESSURE

### ISSUE THREAD

**Issue by rquttaineh** [ferraridamiano/units_converter#6]
Hi There,
Those units are very important for aviation, can you please add them.

Thank you for this great plugin :)

**Comment by ferraridamiano** [comment]
Fixed! I'm not going to release a new version on pub.dev soon. If you need this conversions just add the following to your pubspec.yaml.
```yaml
units_converter:
  git:
    url: https://github.com/ferraridamiano/units_converter/tree/d860e9a791a1251a9c32c31cae48b5bcbd52370a
```

**Comment by rquttaineh** [comment]
Thank you very much for your fast response  👍

**Comment by rquttaineh** [comment]
just a little issue, every (1) inHg should be (33.86388666666671) hPa, you can use this link to check the formula [https://www.convertunits.com/from/hpa/to/inhg](url)

**Comment by ferraridamiano** [comment]
Woooops. I'm so sorry! Just fixed it, thanks!

```yaml
units_converter:
  git:
    url: https://github.com/ferraridamiano/units_converter/tree/7ee378369a75b67e2480eb863850276bb0e83da3
```
